# Generated by Django 2.0.1 on 2018-01-07 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180108_0019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product1',
            new_name='Product',
        ),
    ]
