# Generated by Django 2.0.1 on 2018-01-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20180108_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_of_views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
