# Generated by Django 2.0.1 on 2018-01-11 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_aboutpagetext_contactspagetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='base.ProductType', verbose_name='Тип продукта'),
        ),
    ]
